# Broadcasting
- shape가 다른 배열끼리 연산시(즉, element-wise 연산 불가시) 두 배열의 크기를 동일하게 만들어 연산가능하도록 하는 것.

- ex1. (5,`1`) + (`1`,3) = (5,3)
- ex2. (2,3) + (3,)  = (2,3) + (`2`,3) = (2,3)
- ex3. (5,1) + (3,) = (5,`1`) + (`5`,3) = (5,3) 


In [6]:
import numpy as np

c = np.array([[1], [2], [3], [4]])
d = np.array([5,6,7])
print(c.shape, d.shape, (c+d).shape)
print(c+d)

(4, 1) (3,) (4, 3)
[[ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]
 [ 9 10 11]]
