In [1]:
import numpy as np
a = np.arange(12).reshape(2,3,-1)
print(a)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [4]:
# make [0, 3, 8, 10]
# 0 = [0,0,0]
# 3 = [0,1,1]
# 8 = [1,1,0]
# 10 = [1,2,0] 
a[[0,0,1,1], [0,1,1,2], [0,1,0,0]]

array([ 0,  3,  8, 10])

In [5]:
a = np.arange(12).reshape(4,-1)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [12]:
# make [[1,3], [8,9]]
# 1 = [0,1]
# 3 = [1,0]
# 8 = [2,2]
# 9 = [3,0]
print(a[[0,1,2,3], [1,0,2,0]])
print(a[np.array([[0,1],[2,3]]), 
        np.array([[1,0],[2,0]])
       ])

[1 3 8 9]
[[1 3]
 [8 9]]


In [19]:
a = np.arange(1,7)
b = np.array([True, False, True, True, False, True])
print(a[b])
print(a%2)
print(a%2==0)
print(a[a%2==0]) # boolean array (dtype=bool)
print(a[a%2])    # index array (dtype=int)

[1 3 4 6]
[1 0 1 0 1 0]
[False  True False  True False  True]
[2 4 6]
[2 1 2 1 2 1]


In [20]:
a = np.random.permutation(10)
print(a)
print( a[np.logical_or(a%3==0, a%2==0)] ) # logical_and === &, logical_not === ~
print( a[(a%3==0) | (a%2==0)] )

[4 2 9 5 0 8 1 6 3 7]
[4 2 9 0 8 6 3]
[4 2 9 0 8 6 3]


In [21]:
print(a)
a[a%3==0] = -1
print(a)

[4 2 9 5 0 8 1 6 3 7]
[ 4  2 -1  5 -1  8  1 -1 -1  7]


In [22]:
b = np.arange(1,12,2).reshape(3,-1)
print(b)

[[ 1  3]
 [ 5  7]
 [ 9 11]]


In [24]:
print(b[:,-1])
print(b[:,[-1]]) # array를 index로 주면 원본 shape과 똑같음

[ 3  7 11]
[[ 3]
 [ 7]
 [11]]


In [35]:
c = np.arange(24).reshape(2,3,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [37]:
print(c[:,-1]) # same as c[:,-1,:]

[[ 8  9 10 11]
 [20 21 22 23]]


In [32]:
print(c[...,-1])
print(c[...,:1]) # :1 이 slice 개념이 있으므로 배열임. 그래서 위와는 다르게 차원 줄어들지 않음

[[ 1  3  5]
 [ 7  9 11]]
[[[ 0]
  [ 2]
  [ 4]]

 [[ 6]
  [ 8]
  [10]]]


In [33]:
print(c[[0],1])
print(c[[0],1:])

[[2 3]]
[[[2 3]
  [4 5]]]


In [38]:
aN3 = np.array([[0,-1,4],[-2,3,2],[1,-2,-1],[-4,3,-2]])
print(aN3)

[[ 0 -1  4]
 [-2  3  2]
 [ 1 -2 -1]
 [-4  3 -2]]


In [39]:
aN3[:, [1,0,2]] # 인덱스 순서 바꾸기

array([[-1,  0,  4],
       [ 3, -2,  2],
       [-2,  1, -1],
       [ 3, -4, -2]])

In [ ]:
aN3[aN3[:,0] < 0] # 모든행의 첫번째원소에 대하여 0 미만이면, 해당 행을 살려라