In [1]:
import numpy as np
a = np.arange(12).reshape(2,3,-1)
print(a)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [4]:
# make [0, 3, 8, 10]
# 0 = [0,0,0]
# 3 = [0,1,1]
# 8 = [1,1,0]
# 10 = [1,2,0] 
a[[0,0,1,1], [0,1,1,2], [0,1,0,0]]

array([ 0,  3,  8, 10])

In [5]:
a = np.arange(12).reshape(4,-1)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [11]:
# make [[1,3], [8,9]]
# 1 = [0,1]
# 3 = [1,0]
# 8 = [2,2]
# 9 = [3,0]
print(a[[0,1,2,3], [1,0,2,0]])
print(a[np.array([[0,1],[2,3]]), 
        np.array([[1,0],[2,0]])
       ])

[1 3 8 9]


IndexError: index 3 is out of bounds for axis 1 with size 3